phases:
  install:
    runtime-versions:
      nodejs: 12

# Include only the files required for your application to run.
artifacts:
  files:
    - server.js
    - package.json
    - src/**/*
    - node_modules/**/*

version: 0.2